version: "2"

#
# This compose file can be used to run locally without using the locally installed python or dependencies
#

services:

  datastore:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    ports:
    - 8081:8081
    volumes:
     - datastore:/root/.config
    command: gcloud beta emulators datastore start --host-port=0.0.0.0:8081 --project glowscript-dev

  flask:
    image: us.gcr.io/glowscript-py38/glowscript-flask:latest
    ports:
    - 8080:8080
    links:
     - datastore
    volumes:
     - .:/app
     - datastore:/root/.config
    environment:
     - DATASTORE_EMULATOR_HOST=datastore:8081
     - FLASK_RUN_HOST=0.0.0.0
     - FLASK_RUN_PORT=8080
    command: flask run

volumes:
  datastore:
